[log]
level = "info" 
max_size_one_file = 2048 
name = "consumers.log" # 日志文件
path = "./log/" 

# 数据库
[db]
log_mode = true
master_uri = "user:psss@tcp(host:port)/db_name?charset=utf8mb4&parseTime=True&loc=Local"
max_idle_conns = 10
max_open_conns = 100
slave_uris = ["user:psss@tcp(host:port)/db_name?charset=utf8mb4&parseTime=True&loc=Local"]
type = "mysql"

[redis]
dial_timeout = 50 #ms
hosts = ["host:port"]
password = "pass"
pool_timeout = 60 #second
poolsize = 100 
prefix = "hulk:ztp:man:" 
read_timeout = 5000 #ms
write_timeout = 50 #ms
db = 1

[kafka]
[kafka.task]
group = "hulk_dev_task_2" # group
hosts = ["127.0.0.1:9092"] # kafka 地址
topic_prefix = "hulk_dev_" # kafka topic 前缀
topics = ["task"] 
version = "2.0.0" 

[kafka.thanos]
group = "hulk_dev_thanos_consumers_1" # group
hosts = ["127.0.0.1:9092"] # kafka 地址
topic_prefix = "thanos_dev_" # kafka topic 前缀
topics = [1, 7] 
version = "2.0.0" 

[kafka.upes]
group = "hulk_dev_upes" # group
hosts = ["127.0.0.1:9092"] # kafka 地址
topic_prefix = "hulk_dev_" # kafka topic 前缀
topics = ["upes", "upes", "upes","upes"]
version = "2.0.0"

[es]
host = "http://127.0.0.1:9200"
index = "hulk_pro_task"
# info_log = "log/es_info.log"
# err_log = "log/es_err.log"
# trace_log = "log/es_trace.log"

[influx]
bucket = "hulk-dev"
host = "http://influxdb_host:port"
org = "zsmarter"
token = "xxx"
