[register_server]

[register_server.rpc]
address = ":0" # rpc 地址:端口
name = "thanos_dev_register" # 注册的服务名
reg_hosts = ["127.0.0.1:2181"] # 注册中心地址
reg_interval = 2 # second
reg_ttl = 3 # second
trans_timeout = 10 # second
version = "1.0" 

[kafka_consumer] # 该服务是 kafka 消费者
group = "thanos_dev_register_1" # group
hosts = ["127.0.0.1:9092"] # kafka 地址
topic_prefix = "thanos_dev_" # kafka topic 前缀
topics = [1] 
version = "2.0.0" 

[kafka_producer] # 该服务是 kafka 生产者
hosts = ["127.0.0.1:9092"] # kafka 地址
topic_prefix = "thanos_dev_" # kafka topic 前缀
version = "2.0.0" 

[redis]
dial_timeout = 50 #ms
hosts = ["host:port"] # redis 地址
password = "pass"
pool_timeout = 60 #second
poolsize = 100 
prefix = "hulk:ztp:thanos:" # 服务所有 redis 数据前缀
read_timeout = 5000 #ms
write_timeout = 50 #ms
db = 1

[log]
level = "debug" # debug,info,error
max_size_one_file = 2048 # MB
path = "./log/" # 日志存放路径（相对路径基于可执行文件的路径）

[db]
log_mode = true
master_uri = "ztp_dev:zdev_JG*&@9@tcp(127.0.0.1:3306)/ztp_dev?charset=utf8&parseTime=True&loc=Local"
max_idle_conns = 10
max_open_conns = 100
slave_uris = ["ztp_dev:zdev_JG*&@9@tcp(127.0.0.1:3306)/ztp_dev?charset=utf8&parseTime=True&loc=Local"]
type = "mysql"

[debug]
pprof_port = "0"

[influx]
bucket = "hulk-dev"
host = "http://influxdb_host:port"
org = "zsmarter"
token = "xxx"
